export const FOOD_LOADING = "FOOD_LOADING";
export const FOOD_END_LOADING = "FOOD_END_LOADING";
export const GET_FOODS = "GET_FOODS";
export const GET_FOOD = "GET_FOOD";
export const GET_SEARCH_FOOD = "GET_SEARCH_FOOD";

export const COMMENT_LOADING = "COMMENT_LOADING";
export const COMMENT_END_LOADING = "COMMENT_END_LOADING";
export const GET_COMMENT = "GET_COMMENT";
export const GET_COMMENTS = "GET_COMMENTS";
export const GET_SEARCH_COMMENT = "GET_SEARCH_COMMENT";

export const USER_LOADING = "USER_LOADING";
export const USER_END_LOADING = "USER_END_LOADING";
export const GET_USER = "GET_USER";
export const GET_USERS = "GET_USERS";
export const GET_SEARCH_USER = "GET_SEARCH_USER";

export const PHOTO_LOADING = "PHOTO_LOADING";
export const PHOTO_END_LOADING = "PHOTO_END_LOADING";
export const GET_PHOTO = "GET_PHOTO";
export const GET_PHOTOS = "GET_PHOTOS";
export const GET_SEARCH_PHOTO = "GET_SEARCH_PHOTO";
